version : '3.4'
services:
    model_serving_api:
      image: kosy9/fb_image_classification:latest
      build: .
      ports: 
        - 8080:8080
      restart: always
      # environment:
      #   - BUCKET_NAME=projectstack-9f1749cc-4ba8-4037-ade0-414-datalake-hyh931m8pu4y
      network_mode: host
      volumes: 
        - /Users/mariakosyuchenko/AI_Core/facebook-marketplaces-recommendation-ranking-system:/app